# Generated by Django 5.1.1 on 2024-10-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_client', models.CharField(max_length=10, unique=True, verbose_name='Code client unique')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut de soumission du formulaire')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='FormulaireClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.IntegerField(verbose_name='Question 1')),
                ('q2', models.IntegerField(verbose_name='Question 2')),
                ('q3', models.IntegerField(verbose_name='Question 3')),
                ('q4', models.IntegerField(verbose_name='Question 4')),
                ('q5', models.IntegerField(verbose_name='Question 5')),
                ('q6', models.CharField(max_length=150)),
                ('q7', models.IntegerField(verbose_name='Question 6')),
                ('q8', models.IntegerField(verbose_name='Question 7')),
                ('q9', models.IntegerField(verbose_name='Question 8')),
                ('q10', models.IntegerField(verbose_name='Question 9')),
                ('q11', models.IntegerField(verbose_name='Question 10')),
                ('q12', models.CharField(max_length=255)),
                ('q13', models.IntegerField(verbose_name='Question 11')),
                ('q14', models.IntegerField(verbose_name='Question 12')),
                ('q15', models.CharField(max_length=10)),
                ('q16', models.CharField(max_length=255)),
                ('q17', models.CharField(max_length=10)),
                ('q18', models.CharField(max_length=10)),
                ('q19', models.CharField(blank=True, max_length=255, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('client', models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='formulaire.client', verbose_name='Client associé')),
            ],
            options={
                'db_table': 'formulaire_client',
            },
        ),
    ]
